### ISSUE TITLE
Get rid of the MASTER branch!

### ISSUE THREAD

**Issue by BenNeighbour** [corpm014/Small-multiplayer-game#1]
I'd suggest that you completely purge the ```master``` branch of this project. Not doing this may result in some unexpected weird stuff happening to the repository - so don't take the risk.

You can do this by typing in your terminal:

```
$ git checkout main
```

then delete  the ```master``` branch,

```
$ git branch -d master
```

next, on the ```<>Code``` tab of this repository, click on the main button, then see all branches, then make sure that ```main```  has ```default``` next to it.

Then delete the master branch and you'll be good to go!

**Comment by BenNeighbour** [comment]
Don't worry I did it!

**Comment by corpm014** [comment]
Thanks Ben,
Sorry this is my first time doing pull, commit and push etc.
